site_name: Flask Sugar
site_description: Flask Sugar is a web framework for building APIs with Flask, Pydantic and Python 3.6+ type hints.
theme:
  name: material
  language: en
  palette:
    primary: red
  icon:
    logo: material/candycane
    repo: fontawesome/brands/github
  favicon: img/favicon.ico
  features:
    - navigation.expand
    - navigation.top
    # - navigation.tabs
repo_url: https://github.com/ShangSky/flask-sugar
repo_name: ShangSky/flask-sugar
edit_uri: ""
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.progressbar
  - attr_list
extra:
  alternate:
    - name: English
      link: /en
      lang: en
    - name: 简体中文
      link: zh/
      lang: zh
nav:
  - "Quick Start": index.md
  - Parameters:
    - params/path-params.md
    - params/query-params.md
    - params/cookie-params.md
    - params/header-params.md
    - params/request-body.md
    - params/form-data.md
    - params/file-uploads.md
  - response.md
  - handling-errors.md
  - sugar-parameters.md
  - operation-parameters.md