name: ci
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r dev-requirements.txt
      - name: pyright
        run: pyright flask_sugar
      - name: isort
        run: isort flask_sugar --check
      - name: black
        run: black -v flask_sugar --check
  deploy:
    if: github.repository == 'main'
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
